### ISSUE TITLE
Assigning Market

### ISSUE THREAD

**Issue by shellebusch2** [shellebusch2/DSAllo#11]
The market of an entry should be automatically assigned based on city entry on form (closest market to city)

- get list of all Allo markets (get access from Brian)

UPDATE 10/25/22: 
- Will be having the users tag their own market
- Get a list of all ALLO markets (possibly from Ed)
- Update the Tally complaint form to ask for market

SOLUTION
- Will need to create a markets database in Notion
- Have the Tally complaint form pull the markets from the market database, allow users to select their market

A/C: Markets database is created. When test form is submitted, market is automatically assigned, accurately.

**Comment by ekonnath** [comment]
Current solution is to map the Market value in Make it the following format
`{{if(4.properties_value.City.name = "[city name]"; "[uuid of city on Market DB]"; )}}`
