### ISSUE TITLE
Research/Reconfigure Assigning Urgency

### ISSUE THREAD

**Issue by shellebusch2** [shellebusch2/DSAllo#15]
Research about how to automate assigning the urgency of a complaint. Decide how to decide urgency and how to do this in Notion.
Urgency levels:
```
urgent
non-urgent
```

UPDATE 10/25/22: 
- This will need to be further discussed with Brian for a solution, as different markets have different service level agreements (SLAs)
- Keep story on the backlog for now

Currently complaints come in as DROP, INSTALL, ISP. Is there a way to pipeline that information along with the market to determine urgency level?

A/C:
Documentation or explanation of plan to analyze urgency and how to do this in Notion.

**Comment by shellebusch2** [comment]
When a complaint comes in, urgency level is automatically assigned by semantic analysis.
This includes research on how to perform semantic analysis in Notion.
Urgency levels:

urgent
Non-urgent
A/C:
When complaint is submitted through test form, the correct urgency level is assigned. Includes explanation/documentation of how semantic analysis works.

**Comment by ekonnath** [comment]
WIll try to meet with Brian to discuss this
