### ISSUE TITLE
As an Allo employee, I want complaints submitted to be entered in the database.

### ISSUE THREAD

**Issue by shellebusch2** [shellebusch2/DSAllo#2]
- In order to do anything with the complaints, we need the form to enter them into the database

A/C: When a complaint is submitted on Allo's form, the information enters the accurate database columns
- columns to be entered dependant on completion of database creation

**Comment by hannahpokharel** [comment]
- [ ] test

**Comment by shellebusch2** [comment]
@shellebusch2 create dependency
